# Generated by Django 3.2.9 on 2022-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
