# Generated by Django 3.2.9 on 2022-04-09 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_filemodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='minutes',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='looping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='orderI',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='startTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
