# Generated by Django 3.2.9 on 2022-04-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220409_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
