# Generated by Django 3.2.9 on 2022-04-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_auto_20220425_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileCount', models.CharField(max_length=200)),
                ('looping', models.CharField(default=1, max_length=3)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media/')),
                ('sequence', models.CharField(default=1, max_length=2)),
                ('fileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.filemodel')),
            ],
        ),
    ]
