# Generated by Django 4.0.5 on 2022-07-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_filedata_filemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedata',
            old_name='sequence',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='filedata',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
